# Generated by Django 2.1.1 on 2018-12-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181231_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='title',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task',
            field=models.TextField(max_length=500),
        ),
    ]
