# Generated by Django 2.1.1 on 2019-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181231_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_task', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='DailyTask',
            new_name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='MonthlyTask',
        ),
    ]
