# Generated by Django 2.1.1 on 2019-01-01 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190101_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='monthly_task',
            new_name='goals',
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
