# Generated by Django 2.1.1 on 2019-01-01 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190101_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
