# Generated by Django 2.1.1 on 2019-01-01 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_monthlygoal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
