# Generated by Django 2.1.1 on 2019-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190101_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='task',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='monthlygoal',
            name='goals',
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='goals',
            field=models.ManyToManyField(to='todo.Goals'),
        ),
    ]
