# Generated by Django 2.1.1 on 2019-01-08 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190108_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlygoal',
            name='goals',
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='goals',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
