# Generated by Django 2.1.1 on 2019-01-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190108_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoal',
            name='name',
        ),
    ]
