# Generated by Django 2.1.1 on 2019-01-13 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_dailygoal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
