# Generated by Django 2.1.1 on 2019-01-22 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_dailygoal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
